
	<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		
		  ga('create', 'UA-61934064-1', 'auto');
		  ga('send', 'pageview');
	</script>

	<!-- BEGIN: HEADER -->
	<div id="header" class="transparent">
		<div class="wrapper">
			<div class="logo">
				<a href="<?php echo $this->url->get();?>"><img src="<?php echo PUBLIC_URL.'frontend/images/logo_w.png';?>" /></a>
			</div>
			<div id="menu">
				<div class="menu-navigation">
					<div class="module">
						<div class="modulecontent">
							<div class="menu-navigation">
								<?php if(isset($menu) && !empty($menu)):?>
									<ul class="menu">
										<?php foreach ($menu as $key => $value):?>
											<li class="li_<?= $value->id;?> transparent">
												<a href="<?= ROOT_URL.$value->link;?>"><?= $value->name;?></a>
											</li>
										<?php endforeach;?>
									</ul>
								<?php endif;?>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="social">
				<div class="moduletable">
					<div class="modulecontent">
						<div>
							<a class="ico_mail" onclick="javascript:window.open('mailto:rmtarch@gmail.com');">&nbsp;</a>
							<a class="ico_be" onclick="javascript:window.open('https://www.behance.net/rMtArc','_blank');" target="_blank">&nbsp;</a>
							<a class="ico_fb" onclick="javascript:window.open('https://www.facebook.com/rmtarc','_blank');" target="_blank">&nbsp;</a>
						</div>
					</div>
				</div>
			</div>												
			<div class="clr"></div>
		</div>
	</div>
	<!-- END: HEADER -->

	<!-- BEGIN: MAIN-CONTNENT -->
	<div id="main-body">
		<div id="main-content">
			<div class="wrapper">
				<div id="center">
					<?php echo $this->getContent();?>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
	<!-- END: MAIN-CONTNENT -->

	<!-- BEGIN: FOOTER -->
	<div id="footer">
		<div class="wrapper">
			<div id="copyright">
				<p>&copy Copyright 2015 Rmt Studio</p>
				<p><a class="ico_share" onclick="javascript:fbShare('<?php echo 'http://'.$_SERVER['HTTP_HOST'].$this->url->get();?>', 'Fb Share', 'Facebook share popup', '', 520, 350)">&#160;</a><a class="ico_like" href="">&#160;</a></p>
			</div>
		</div>
	</div>
	<!-- END: FOOTER -->

	<script type="text/javascript">
		$(window).scroll(function(){
            if ($(window).scrollTop() > 10) {
				$("#header").removeClass('transparent');
				$("ul.menu a").removeClass('transparent');
            }
            else {
				$("#header").addClass('transparent');
				$("ul.menu a").addClass('transparent');
            }
	    });
	</script>

	<script>
		(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&appId=1612798012281737&version=v2.0";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));

	    function fbShare(url, title, descr, image, winWidth, winHeight) {
	        var winTop = (screen.height / 2) - (winHeight / 2);
	        var winLeft = (screen.width / 2) - (winWidth / 2);
	        window.open('http://www.facebook.com/sharer.php?app_id=1489595237990958&sdk=joey&u=' + url + '&ref=plugin', 'sharer', 'top=' + winTop + ',left=' + winLeft + ',toolbar=0,status=0,width=' + winWidth + ',height=' + winHeight);
	    }
	</script>