<?= $this->tag->form(array('method'=>'get')); ?>
	<div class="search">
		<input type="text" name="<?= $column_search ?>" value="<?= $value_search ?>">
		<input type="submit" class="btn" value="Tìm kiếm">
		<?= $this->tag->linkTo(array("{$uri}clear", 'Làm mới', 'class'=>'btn'));?>
	</div>
</form>

<?= $this->tag->form("{$uri}index"); ?>
	<div class="toolbar">
		<?= $this->tag->linkTo(array("{$uri}add", 'Thêm mới','class'=>'toolbar_btn add'))?>
		<input type="submit" name="active" value="Kích hoạt" class="toolbar_btn active">
		<input type="submit" name="no_active" value="Đóng" class="toolbar_btn no_active">
		<input type="submit" name="order" value="Sắp xếp" class="toolbar_btn order">
		<input type="submit" name="delete" value="Xóa" class="toolbar_btn delete">
	</div>
	<div style="clear:both;"></div>
	<?php $this->flashSession->output() ?>
	<div class="module width_full">
		<div class="module_header">
			<h3 class="table_title">Danh sách</h3>
		</div>
		<div class="table_container">
			<div class="table_content" id="tab1" style="display: block;">
				<table cellspacing="0" cellspacing="0" border="0" class="table_main"> 
					<thead> 
						<tr> 
							<th class="header" style="width:20px;">#</th> 
							<th class="header" style="width:30px;"><input type="checkbox"  onchange="togglecheckboxes(this,'cbgroup1')" value=""></th> 
							<th class="header"><?= $this->tag->linkTo(array("{$uri}index{$page}&column=name{$order}","Tên","class"=>"{$system->getIconPosition("name")}"))?></th> 
							<th class="header">Mã quyền</th>
							<?php foreach($action as $k => $v): ?>
								<th class="header"><?= $v ?></th>
							<?php endforeach; ?> 
							<th class="header" style="width:40px;">Xóa</th> 
						</tr> 
					</thead>
					<tbody> 
						<?php foreach ($role as $key => $value) { ?>
							<tr>
								<td rowspan="<?= count($value)+1 ?>"><?= $stt++ ?></td>
								<td rowspan="<?= count($value)+1 ?>"><input type="checkbox" id="cb1_<?= $key ?>" name="checkbox[]" class="cbgroup1" value="<?= $value->id ?>"></td> 
								<td rowspan="<?= count($value)+1 ?>" style="border-right:1px solid #d4dce6"><?= $this->tag->linkTo(array("{$uri}edit/{$key}","{$group_detail->getDetailGroup($key)->name}")) ?></td>
							</tr>
							<?php foreach($value as $k_1 => $v_1): ?>
								<tr>
									<td><?= $k_1 ?></td>
									<?php foreach($action as $k_action => $v_action): ?>
										<td>
											<?php if(isset($v_1[$k_action])): ?>
												<?= $this->tag->linkTo(array("{$uri}","",'class'=>"icn {$plugin->getStatusDetail(1)}"))?>
											<?php else: ?>
												<?= $this->tag->linkTo(array("{$uri}","",'class'=>"icn {$plugin->getStatusDetail(0)}"))?>
											<?php endif; ?>
										</td>
									<?php endforeach; ?>
									
									<td><?= $this->tag->linkTo(array("{$uri}deleteRole/{$key}/{$k_1}","Tên","class"=>"icn gp_delete","title"=>"<b> {$group_detail->getDetailGroup($key)->name} - {$k_1}</b>")) ?></td>
								</tr>
							<?php endforeach; ?>
							
						<?php } ?>
					</tbody> 
				</table>
			</div>
		</div>
	</div>
		
</form>