<div class="news news-list">
	<div class="module">
		<div class="moduletitle">
			<h3><?php echo (isset($category->title) && !empty($category->title)) ? $category->title : 'Tin tức'; ?></h3>
		</div>
		
		<div class="modulecontent">
			<?php if($list_item): ?>
				<?php foreach($list_item as $key => $value): ?>
					<div class="item">
						<!-- IMAGE -->
						<?php if(isset($value->image) && !empty($value->image)):?>
							<div class="image">
								<?= $this->tag->linkTo(array('tin-tuc/'.$value->news_category->code.'/'.$value->code, '<img src="'.$this->url->get().$value->image.'">')); ?>
							</div>
						<?php endif;?>

						<!-- TITLE -->
						<div class="title">
							<h3><?= $this->tag->linkTo(array('tin-tuc/'.$value->news_category->code.'/'.$value->code, $this->plugin->getCutString($value->title, 100))); ?></h3>
						</div>

						<!-- DESCRIPTION -->
						<div class="description">
							<?php echo $this->plugin->getCutString($value->description, 200);?>
						</div>
					</div>
					<div class="clear"></div>
				<?php endforeach; ?>
			<?php endif; ?>

			<div class="paginator">
				<?php echo $paginator ?>
			</div>
		</div>
	</div>
</div>