	<?php $this->flashSession->output() ?>
	<div class="module width_full">
		<?= $this->tag->form("{$uri}add/".$menu_id); ?>
			<div class="module_header">
				<h3 class="table_title"><?= $title_action; ?></h3>
			</div>
			
			<div class="module_content">
				<ul class="tab-row">
					<li>Thông tin chính</li>
				</ul>
				<div class="tab-group">
					<fieldset class="tab-content main">
						<div class="row hor">
							<label>Tên</label>
							<?php $is_error = isset($error) && in_array("name", $error) ? "error":"" ?>
							<?= $form->render("name", array("class"=>"txt_long {$is_error}")) ?>
						</div>
						<div class="row hor">
							<label>Code</label>
							<?= $form->render("code", array("readonly"=>true, "class"=>"txt_long")) ?>
						</div>
						<div class="row hor">
							<label>Liên kết</label>
							<?php $is_error = isset($error) && in_array("link", $error) ? "error":"" ?>
							<?= $form->render("link", array("class"=>"txt_long {$is_error}")) ?>
						</div>
						<div class="row hor half">
							<label>Menu cha</label>							
							<?= $form->render("parents", array("class"=>"medium listbox", "size"=>9, 'multiple'=>true)); ?>
						</div>
						<div class="row hor half">
							<label>Thuộc menu</label>
							<?= $form->render("menu_id", array("class"=>"medium")) ?>
						</div>
						<div class="row hor half">
							<label>Kích hoạt</label>
							<?= $form->render("status", array("class"=>"medium")); ?>
						</div>
						<div class="row hor half">
							<label>Cửa sổ mới</label>
							<?= $form->render("target", array("class"=>"medium")); ?>
						</div>
						<div class="row hor half">
							<label>Hình ảnh</label>
							<?= $form->render("image", array("class"=>"txt_medium button")); ?>
							<span class="input-group-btn">
		                    	<button type="button" class="btn btn-default fileBrowse" data-target="image"><i class="fa fa-folder-open"></i> Browse</button>
		                    </span>
						</div>
						<div class="row hor half">
							<label>Thứ tự</label>
							<?= $form->render("position", array("class"=>"txt_medium")); ?>
						</div>
					</fieldset>
				</div>
			</div>
			<footer>
				<div class="submit_link">
					<input type="submit" value="Thêm mới" class="btn">
					<?= $this->tag->linkTo(array("{$uri}index/".$menu_id, 'Trở lại', 'class'=>'btn'));?>
				</div>
			</footer>
		</form>
	</div>
