	<?php $this->flashSession->output() ?>
	<div class="module width_full">
		<?= $this->tag->form("{$uri}edit/{$form->getValue('id')}"); ?>
			<div class="module_header">
				<h3 class="table_title"><?= $title_action; ?></h3>
			</div>
			
			<div class="module_content">
				<ul class="tab-row">
					<li>Thông tin chính</li>
					<li>Cấu hình</li>
				</ul>
				<div class="tab-group">
					<fieldset class="tab-content main">
						<div class="row hor">
							<label>Tiêu đề</label>
							<?php $is_error = isset($error) && in_array("name", $error) ? "error":"" ?>
							<?= $form->render("name", array("class"=>"txt_long {$is_error}")) ?>
						</div>
						<div class="row hor half">
							<label>Menu</label>
							<?= $form->render("menu_id", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Kích hoạt</label>
							<?= $form->render("status", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Thuộc menu item</label>
							<?= $form->render("parents", array("class"=>"medium listbox", "size"=>10)); ?>
						</div>
						<div class="row hor half">
							<label>Loại</label>
							<?php $is_error = isset($error) && in_array("type", $error) ? "error":"" ?>
							<?= $form->render("type", array("class"=>"long {$is_error}")) ?>
						</div>
						<div class="row hor half">
							<label>Hình ảnh</label>
							<?= $form->render("image", array("class"=>"txt_long button")) ?>
							<span class="input-group-btn">
								<button type="button" class="btn btn-default fileBrowse" data-target="image"><i class="fa fa-folder-open"></i> Browse</button>
							</span>
						</div>
						<div class="row hor half">
							<label>Thứ tự</label>
							<?= $form->render("position", array("class"=>"long")) ?>
						</div>
					</fieldset>

					<fieldset class="tab-content config">
						<div class="row hor half">
							<label>Kiểu mở trang</label>
							<?= $form->render("target", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Ngôn ngữ</label>
							<?= $form->render("language", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Thuộc kênh thông tin</label>
							<?= $form->render("params[category][]", array('multiple'=>'multiple',"class"=>"medium listbox", "size"=>10)); ?>
						</div>
						<div class="row hor half">
							<label>Bài viết</label>
							<?= $form->render("params[articleID]", array("class"=>"txt_long", "rows"=>12, 'style'=>'width:94%')) ?>
						</div>
						<div class="row hor half">
							<label>Dạng hiển thị</label>
							<?= $form->render("params[show]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Số phần tử</label>
							<?= $form->render("params[items]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Hiển thị ảnh</label>
							<?= $form->render("params[show_image]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Liên kết ảnh</label>
							<?= $form->render("params[link_image]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Hiển thị tiêu đề</label>
							<?= $form->render("params[show_title]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Liên kết tiêu đề</label>
							<?= $form->render("params[link_title]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Số ký tự tiêu đề</label>
							<?= $form->render("params[number_title]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Hiển thị tóm tắt</label>
							<?= $form->render("params[show_description]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Liên kết tóm tắt</label>
							<?= $form->render("params[link_description]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Số ký tự tóm tắt</label>
							<?= $form->render("params[number_description]", array("class"=>"txt_long")) ?>
						</div>
						<div class="row hor half">
							<label>Hiển thị ngày đăng</label>
							<?= $form->render("params[show_published]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Hiển thị lượt xem</label>
							<?= $form->render("params[show_hits]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Phân trang</label>
							<?= $form->render("params[show_paginator]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Kiểu phân trang</label>
							<?= $form->render("params[style_paginator]", array("class"=>"long")) ?>
						</div>
					</fieldset>
				</div>
			</div>
			<footer>
				<div class="submit_link">
					<input type="submit" value="Lưu" class="btn">
					<?= $this->tag->linkTo(array("{$uri}index", 'Trở lại', 'class'=>'btn'));?>
				</div>
			</footer>
		</form>
	</div>

	<script type="text/javascript">
		
        $("ul.tab-row li:first").addClass("active");
        $(".tab-group .tab-content:gt(0)").hide();
        $("ul.tab-row li").click(function(){
            $("ul.tab-row li").removeClass('active');
            var current_index = $("ul.tab-row li").index(this);
            $("ul.tab-row li:eq("+current_index+")").addClass("active");
            $(".tab-group .tab-content").hide();
            $(".tab-group .tab-content:eq("+current_index+")").fadeIn();
        });

	</script>
