	<?php $this->flashSession->output() ?>
	<h4 class="alert_info">Welcome to the free MediaLoot admin panel template, this could be an informative message.</h4>

	<article class="module width_full">
		<header><h3>Stats</h3></header>
		<div class="module_content">
			<article class="stats_graph">
				
			</article>
			
			<article class="stats_overview">
				<div class="overview_today">
					<p class="overview_day">Today</p>
					<p class="overview_count">1,876</p>
					<p class="overview_type">Hits</p>
					<p class="overview_count">2,103</p>
					<p class="overview_type">Views</p>
				</div>
				<div class="overview_previous">
					<p class="overview_day">Yesterday</p>
					<p class="overview_count">1,646</p>
					<p class="overview_type">Hits</p>
					<p class="overview_count">2,054</p>
					<p class="overview_type">Views</p>
				</div>
			</article>
			<div class="clear"></div>
		</div>
	</article>