	<?php $this->flashSession->output() ?>
	<div class="module width_full">
		<?= $this->tag->form("{$uri}add"); ?>
			<div class="module_header">
				<h3 class="table_title"><?= $title_action; ?></h3>
			</div>
			
			<div class="module_content">
				<ul class="tab-row">
					<li>Thông tin chính</li>
					<li>Hình ảnh</li>
				</ul>
				<div class="tab-group">
					<fieldset class="tab-content main">
						<div class="row hor">
							<label>Tiêu đề</label>
							<?php $is_error = isset($error) && in_array("title", $error) ? "error":"" ?>
							<?= $form->render("title", array("class"=>"txt_long {$is_error}")) ?>
						</div>
						<div class="row hor half">
							<label>Album</label>
							<?= $form->render("album_id", array("class"=>"long listbox", 'size'=>9)) ?>
						</div>
						<div class="row hor half">
							<label>Kích hoạt</label>
							<?= $form->render("status", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Nổi bật</label>
							<?= $form->render("featured", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Hình ảnh</label>
							<?= $form->render("image", array("class"=>"txt_long button")) ?>
							<span class="input-group-btn">
								<button type="button" class="btn btn-default fileBrowse" data-target="image"><i class="fa fa-folder-open"></i> Browse</button>
							</span>
						</div>
						<div class="row hor">
							<label>Nội dung</label>
							<?= $form->render("content", array("class"=>"txt_long")) ?>
						</div>
					</fieldset>

					<fieldset class="tab-content select_image">
						<div class="row hor half">
							<input type="hidden" id="select_image" name="attr_image" value="" />
							<span class="input-group-btn">
								<button type="button"  class="btn btn-default" onClick="setImage(this)" data-target="select_image"><i class="fa fa-folder-open"></i> Chọn ảnh</button>
							</span>
							<div class="data_image"></div>
						</div>
					</fieldset>
				</div>
			</div>
			<footer>
				<div class="submit_link">
					<input type="submit" value="Thêm mới" class="btn">
					<?= $this->tag->linkTo(array("{$uri}index", 'Trở lại', 'class'=>'btn'));?>
				</div>
			</footer>
		</form>
	</div>
	
	<script type="text/javascript">
		var sourc = new Array();
		var item = 0;
	</script>