	<?php $this->flashSession->output() ?>
	<div class="module width_full">
		<?= $this->tag->form("{$uri}add"); ?>
			<div class="module_header">
				<h3 class="table_title"><?= $title_action; ?></h3>
			</div>
			
			<div class="module_content">
				<ul class="tab-row">
					<li>Thông tin chính</li>
					<li>Cấu hình</li>
					<li>hình ảnh</li>
				</ul>
				<div class="tab-group">
					<fieldset class="tab-content main">
						<div class="row hor">
							<label>Tiêu đề</label>
							<?php $is_error = isset($error) && in_array("title", $error) ? "error":"" ?>
							<?= $form->render("title", array("class"=>"txt_long {$is_error}")) ?>
						</div>
						<div class="row hor half">
							<label>Album</label>
							<?= $form->render("album_id", array("class"=>"long listbox", 'size'=>9)) ?>
						</div>
						<div class="row hor half">
							<label>Kích hoạt</label>
							<?= $form->render("status", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Nổi bật</label>
							<?= $form->render("feature", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Hình ảnh</label>
							<?= $form->render("image", array("class"=>"txt_long button")) ?>
							<span class="input-group-btn">
								<button type="button" class="btn btn-default fileBrowse" data-target="image"><i class="fa fa-folder-open"></i> Browse</button>
							</span>
						</div>
						<div class="row hor">
							<label>Nội dung</label>
							<?= $form->render("content", array("class"=>"txt_long")) ?>
						</div>
					</fieldset>

					<fieldset class="tab-content config">
						<div class="row hor half">
							<label>Hiển thị tiêu đề</label>
							<?= $form->render("params[show_title]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Hiển thị nội dung</label>
							<?= $form->render("params[show_content]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Hiển thị ngày đăng tải</label>
							<?= $form->render("params[show_published]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Hiển thị lượt xem</label>
							<?= $form->render("params[show_hits]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half" id="datetimepicker">
							<label class="control-label">Ngày đăng</label>
			                <div class='input-group date input-append' id="datetimepicker">
								<?= $form->render('published', array("class"=>"txt_medium button")) ?>
			                    <span class="input-group-addon add-on"><i data-date-icon="icon-calendar" data-time-icon="icon-time" class="fa fa-calendar">b</i></span>
			                </div>
						</div>
						<div class="row hor half">
							<label>Thứ tự</label>
							<?= $form->render("position", array("class"=>"txt_medium")) ?>
						</div>
					</fieldset>

					<fieldset class="tab-content select_image">
						<div class="row hor half">
							<input type="hidden" id="select_image" name="attr_image" value="" />
							<span class="input-group-btn">
								<button type="button"  class="btn btn-default" onClick="setImage(this)" data-target="select_image"><i class="fa fa-folder-open"></i> Chọn ảnh</button>
							</span>
							<div class="data_image"></div>
						</div>
					</fieldset>
				</div>
			</div>
			<footer>
				<div class="submit_link">
					<input type="submit" value="Thêm mới" class="btn">
					<?= $this->tag->linkTo(array("{$uri}index", 'Trở lại', 'class'=>'btn'));?>
				</div>
			</footer>
		</form>
	</div>
	
	<script type="text/javascript">
		var sourc = new Array();
		var item = 0;
		var published = "<?= $form->getValue('published')!=""?$form->getValue('published'):date("Y-m-d H:i:s")?>";
	</script>