
<?= $this->tag->stylesheetLink("backend/css/popup.css"); ?>

<!-- BEGIN: header bar -->
<div id="header">
	<h1 class="site_title"><a href="#"><?php echo (isset($site_title) && !empty($site_title)) ? $site_title : 'Administrator';?></a></h1>
	<h2 class="module_title"><?php echo (isset($module_title) && !empty($module_title)) ? $module_title : '';?></h2>
</div>
<!-- END: header bar -->

<!-- BEGIN: main -->
<div id="main" class="column">
	<div class="module">
		<?php foreach ($list_item as $key => $value):?>
			<div class="row">
				<?php $temp = explode('.', $value->type);?>
				<?= $this->tag->linkTo(array(	
												'admin/'.$temp[0].'-config/addelement/'.$temp[1],
												$value->name,
												'target'=>'_parent',
											)
										);
				?>
			</div>
		<?php endforeach;?>
		<div class="clear"></div>
	</div>
</div>
<!-- END: main -->

				