
	<div id="home">
		<div class="page">

			<div id="header">
				<div class="wrapper">
					<div class="logo">
						<a href="<?php echo $this->url->get();?>"><img src="<?php echo PUBLIC_URL.'/frontend/images/logo_w.png';?>" /></a>
					</div>
					<div id="menu">
						<div class="menu-navigation">
							<?php $this->menu->show('menu-top');?>
						</div>
					</div>
					<div class="social">
						<div class="moduletable">
							<div class="modulecontent">
								<div>
									<a class="ico_mail" onclick="javascript:window.open('mailto:rmtarch@gmail.com');">&nbsp;</a>
									<a class="ico_be" onclick="javascript:window.open('https://www.behance.net/rMtArc','_blank');" target="_blank">&nbsp;</a>
									<a class="ico_fb" onclick="javascript:window.open('https://www.facebook.com/rmtarc','_blank');" target="_blank">&nbsp;</a>
								</div>
							</div>
						</div>
					</div>												
					<div class="clr"></div>
				</div>
			</div>

			<div class="slideshow">
				<?php $this->element->image_slick(5, 1);?>
			</div>

		</div>
	</div>