	<?php $this->flashSession->output() ?>
	<div class="module width_full">
		<?= $this->tag->form("{$uri}add"); ?>
			<div class="module_header">
				<h3 class="table_title"><?= $title_action; ?></h3>
			</div>
			
			<div class="module_content">
				<fieldset>
					<div class="row">
						<label>Tên đăng nhập</label>
						<?php $is_error = isset($error) && in_array("username", $error) ? "error":"" ?>
						<?= $form->render("username", array("class"=>"txt_medium {$is_error}")) ?>
					</div>
					<div class="row">
						<label>Email</label>
						<?php $is_error = isset($error) && in_array("email", $error) ? "error":"" ?>
						<?= $form->render("email", array("class"=>"txt_medium {$is_error}")) ?>
					</div>
					<div class="row">
						<label>Mật khẩu</label>
						<?php $is_error = isset($error) && in_array("password", $error) ? "error":"" ?>
						<?= $form->render("password", array("class"=>"txt_medium {$is_error}")) ?>
					</div>
				
					<div class="row">
						<label>Bộ phận</label>
						<?= $form->render("department_id", array("class"=>"medium")) ?>
					</div>
					<div class="row">
						<label>Nhóm quyền</label>
						<?= $form->render("group_id", array("class"=>"medium")) ?>
					</div>
					<div class="row">
						<label>Kích hoạt</label>
						<?= $form->render("status", array("class"=>"medium")) ?>
					</div>
				</fieldset>
			</div>
			<footer>
				<div class="submit_link">
					<input type="submit" value="Thêm mới" class="btn">
					<?= $this->tag->linkTo(array("{$uri}index", 'Trở lại', 'class'=>'btn'));?>
				</div>
			</footer>
		</form>
	</div>