
	<!-- <div class="featured-image">
		<?php //if($list_image): ?>
			<ul>
				<?php //foreach ($list_image as $key => $value): ?>
					<li>
						<a href="">
							<img src="<?php //echo PUBLIC_URL.$value->image;?>" alt="Work">
						</a>
					</li>					
				<?php //endforeach;?>
			</ul>
		<?php //endif;?>
	</div> -->

	<div class="container">
		<?php if($list_item): ?>
			<ul class="grid effect-1" id="grid">
				<?php foreach ($list_item as $key => $value): ?>
					<li class="work-item">
						<a class="fancybox" rel="gallery<?php echo $value->id;?>" href="<?php echo PUBLIC_URL.'/'.$value->image;?>">
							<div class="work-img">
								<img class="work-img" src="<?php echo PUBLIC_URL.'/'.$value->image;?>">
							</div>
							<div class="work-intro">
                                <h3 class="work-title"><?php echo $value->title;?></h3>
                                <div class="work-descr"><?php echo $value->content;?></div>
                            </div>
						</a>
						<?php if(isset($value->attr_image) && !empty($value->attr_image)):?>
							<div class="hidden">
								<?php $arr_img = explode(',', $value->attr_image);?>
								<?php foreach ($arr_img as $key_1 => $value_1): ?>
									<a class="fancybox" rel="gallery<?php echo $value->id;?>" href="<?php echo PUBLIC_URL.'/'.$value_1;?>"><img src="<?php echo PUBLIC_URL.'/'.$value_1;?>"></a>
								<?php endforeach;?>
							</div>
						<?php endif;?>
					</li>
				<?php endforeach;?>
			</ul>
		<?php endif;?>
	</div>