	<?php $this->flashSession->output() ?>
	<div class="module width_full">
		<?= $this->tag->form("{$uri}addmenu/{$type}/{$menu_id}"); ?>
			<div class="module_header">
				<h3 class="table_title"><?= $title_action; ?></h3>
			</div>
			
			<div class="module_content">
				<ul class="tab-row">
					<li>Thông tin chính</li>
					<li>Cấu hình</li>
				</ul>
				<div class="tab-group">
					<fieldset class="tab-content main">
						<div class="row hor">
							<label>Tên</label>
							<?= $this->tag->textField(array('name', 'class'=>'txt_long'));?>
						</div>
						<div class="row hor half">
							<label>Menu cha</label>
							<?= $this->tag->selectStatic(array('parents', $parents, 'size'=>14, 'multiple'=>true, 'class'=>'medium listbox'));?>
						</div>
						<div class="row hor half">
							<label>Thuộc menu</label>
							<?= $this->tag->selectStatic(array('menu_id', array($menu->id => $menu->name), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Kích hoạt</label>
							<?= $this->tag->setDefaults(array('status'=>1));?>
							<?= $this->tag->selectStatic(array('status', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Cửa sổ mới</label>
							<?= $this->tag->setDefaults(array('target'=>1));?>
							<?= $this->tag->selectStatic(array('target', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Hình ảnh</label>
							<?= $this->tag->textField(array('image', 'class'=>'button'));?>
							<span class="input-group-btn">
		                    	<button type="button" class="btn btn-default fileBrowse" data-target="image"><i class="fa fa-folder-open"></i> Browse</button>
		                    </span>
						</div>
					</fieldset>

					<fieldset class="tab-content config">
						<div class="row hor half">
							<label>Kênh thông tin</label>
							<?= $this->tag->selectStatic(array('params[category][]', $category, 'size'=>13, 'multiple'=>true, 'class'=>'medium listbox'));?>
						</div>
						<div class="row hor half">
							<label>Dạng hiển thị</label>
							<?php $options = array(0=>'Danh sách bài viết', 1=>'Kênh thông tin - bài viết');?>
							<?= $this->tag->selectStatic(array('params[show]', $options, 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Số phần tử</label>
							<?= $this->tag->textField(array('params[items]', 'class'=>'txt_long'));?>
						</div>
						<div class="row hor half">
							<label>Hiển thị ảnh</label>
							<?= $this->tag->setDefaults(array('params[show_image]'=>1));?>
							<?= $this->tag->selectStatic(array('params[show_image]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Liên kết ảnh</label>
							<?= $this->tag->setDefaults(array('params[link_image]'=>1));?>
							<?= $this->tag->selectStatic(array('params[link_image]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Hiển thị tiêu đề</label>
							<?= $this->tag->setDefaults(array('params[show_title]'=>1));?>
							<?= $this->tag->selectStatic(array('params[show_title]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Liên kết tiêu đề</label>
							<?= $this->tag->setDefaults(array('params[link_title]'=>1));?>
							<?= $this->tag->selectStatic(array('params[link_title]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Số ký tự tiêu đề</label>
							<?= $this->tag->setDefaults(array('params[number_title]'=>0));?>
							<?= $this->tag->textField(array('params[number_title]', 'class'=>'txt_long'));?>
						</div>
						<div class="row hor half">
							<label>Hiển thị tóm tắt</label>
							<?= $this->tag->setDefaults(array('params[show_description]'=>0));?>
							<?= $this->tag->selectStatic(array('params[show_description]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Liên kết tóm tắt</label>
							<?= $this->tag->setDefaults(array('params[link_description]'=>0));?>
							<?= $this->tag->selectStatic(array('params[link_description]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Số ký tự tóm tắt</label>
							<?= $this->tag->setDefaults(array('params[number_description]'=>0));?>
							<?= $this->tag->textField(array('params[number_description]', 'class'=>'txt_long'));?>
						</div>
						<div class="row hor half">
							<label>Hiển thị ngày đăng tải</label>
							<?= $this->tag->setDefaults(array('params[show_published]'=>0));?>
							<?= $this->tag->selectStatic(array('params[show_published]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Hiển thị lượt xem</label>
							<?= $this->tag->setDefaults(array('params[show_hits]'=>0));?>
							<?= $this->tag->selectStatic(array('params[show_hits]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
					</fieldset>
				</div>
			</div>
			<footer>
				<div class="submit_link">
					<input type="submit" value="Thêm mới" class="btn">
					<?= $this->tag->linkTo(array("admin/menu-item/show/{$menu_id}", 'Trở lại', 'class'=>'btn'));?>
				</div>
			</footer>
		</form>
	</div>