	<?php $this->flashSession->output() ?>
	<div class="module width_full">
		<?= $this->tag->form("{$uri}addmenu"); ?>
			<div class="module_header">
				<h3 class="table_title"><?= $title_action; ?></h3>
			</div>
			
			<div class="module_content">
				<ul class="tab-row">
					<li>Thông tin chính</li>
					<li>Cấu hình</li>
				</ul>
				<div class="tab-group">
					<fieldset class="tab-content main">
						<div class="row hor">
							<label>Tên</label>
							<?php $is_error = isset($error) && in_array("name", $error) ? "error":"" ?>
							<?= $form->render("name", array("class"=>"txt_long {$is_error}")) ?>
						</div>
						<div class="row hor half">
							<label>Thuộc menu</label>
							<?= $form->render("menu_item", array("class"=>"medium listbox", "size"=>14)); ?>
						</div>
						<div class="row hor half">
							<label>Menu cha</label>
							<?= $form->render("menu", array("class"=>"medium")); ?>
						</div>
						<div class="row hor half">
							<label>Kích hoạt</label>
							<?= $form->render("status", array("class"=>"medium")); ?>
						</div>
						<div class="row hor half">
							<label>Cửa sổ mới</label>
							<?= $form->render("target", array("class"=>"medium")); ?>
						</div>
						<div class="row hor half">
							<label>Hình ảnh</label>
							<?= $form->render("image", array("class"=>"txt_medium button")); ?>
							<span class="input-group-btn">
		                    	<button type="button" class="btn btn-default fileBrowse" data-target="image"><i class="fa fa-folder-open"></i> Browse</button>
		                    </span>
						</div>
					</fieldset>

					<fieldset class="tab-content config">
						<div class="row hor half">
							<label>Kênh thông tin</label>
							<?= $form->render("params[category][]", array("class"=>"medium listbox", "size"=>13)); ?>
						</div>
						<div class="row hor half">
							<label>Dạng hiển thị</label>
							<?= $form->render("params[show]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Số phần tử</label>
							<?= $form->render("params[items]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Hiển thị ảnh</label>
							<?= $form->render("params[show_image]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Liên kết ảnh</label>
							<?= $form->render("params[link_image]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Hiển thị tiêu đề</label>
							<?= $form->render("params[show_title]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Liên kết tiêu đề</label>
							<?= $form->render("params[link_title]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Số ký tự tiêu đề</label>
							<?= $form->render("params[number_title]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Hiển thị tóm tắt</label>
							<?= $form->render("params[show_description]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Liên kết tóm tắt</label>
							<?= $form->render("params[link_description]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Số ký tự tóm tắt</label>
							<?= $form->render("params[number_description]", array("class"=>"txt_long")) ?>
						</div>
						<div class="row hor half">
							<label>Hiển thị ngày đăng tải</label>
							<?= $form->render("params[show_published]", array("class"=>"long")) ?>
						</div>
						<div class="row hor half">
							<label>Hiển thị lượt xem</label>
							<?= $form->render("params[show_hits]", array("class"=>"long")) ?>
						</div>
					</fieldset>
				</div>
			</div>
			<footer>
				<div class="submit_link">
					<input type="submit" value="Thêm mới" class="btn">
					<?= $this->tag->linkTo(array("admin/menu-item/show/{$menu_id}", 'Trở lại', 'class'=>'btn'));?>
				</div>
			</footer>
		</form>
	</div>