	<?php $this->flashSession->output() ?>
	<div class="module width_full">
		<?= $this->tag->form("{$uri}/editmenu/{$menu_item->id}"); ?>
			<div class="module_header">
				<h3 class="table_title"><?= $title_action; ?></h3>
			</div>
			
			<div class="module_content">
				<ul class="tab-row">
					<li>Thông tin chính</li>
					<li>Cấu hình</li>
				</ul>
				<div class="tab-group">
					<fieldset class="tab-content main">
						<div class="row hor">
							<label>Tên</label>
							<?= $this->tag->setDefaults(array('name'=>$menu_item->name));?>
							<?= $this->tag->textField(array('name', $menu_item->name, 'class'=>'txt_long'));?>
						</div>
						<div class="row hor half">
							<label>Menu cha</label>
							<?= $this->tag->setDefaults(array('parents'=>$menu_item->parents));?>
							<?= $this->tag->selectStatic(array('parents', $parents, 'size'=>14, 'multiple'=>true, 'class'=>'medium listbox'));?>
						</div>
						<div class="row hor half">
							<label>Thuộc menu</label>
							<?= $this->tag->selectStatic(array('menu_id', array($menu->id => $menu->name), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Kích hoạt</label>
							<?= $this->tag->setDefaults(array('status'=>$menu_item->status));?>
							<?= $this->tag->selectStatic(array('status', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Cửa sổ mới</label>
							<?= $this->tag->setDefaults(array('target'=>$menu_item->target));?>
							<?= $this->tag->selectStatic(array('target', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Hình ảnh</label>
							<?= $this->tag->setDefaults(array('image'=>$menu_item->image));?>
							<?= $this->tag->textField(array('image', 'class'=>'button'));?>
							<span class="input-group-btn">
		                    	<button type="button" class="btn btn-default fileBrowse" data-target="image"><i class="fa fa-folder-open"></i> Browse</button>
		                    </span>
						</div>
					</fieldset>

					<fieldset class="tab-content config">
						<div class="row hor half">
							<label>Kênh thông tin</label>
							<?php $temp = explode(',', $params['category']);?>
							<?php $this->tag->setDefaults(array('params[category][]'=>$temp));?>
							<?= $this->tag->selectStatic(array('params[category][]', $category, 'size'=>9, 'multiple'=>true, 'class'=>'medium listbox'));?>
						</div>
						<div class="row hor half">
							<label>Dạng hiển thị</label>
							<?php $options = array(0=>'Kênh thông tin - bài viết', 1=>'Danh sách bài viết');?>
							<?= $this->tag->setDefaults(array('params[show]'=>$params['show']));?>
							<?= $this->tag->selectStatic(array('params[show]', $options, 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Số phần tử</label>
							<?= $this->tag->setDefaults(array('params[items]'=>$params['items']));?>
							<?= $this->tag->textField(array('params[items]', 'class'=>'txt_long'));?>
						</div>
						<div class="row hor half">
							<label>Hiển thị ảnh</label>
							<?= $this->tag->setDefaults(array('params[show_image]'=>1));?>
							<?= $this->tag->setDefaults(array('params[show_image]'=>$params['show_image']));?>
							<?= $this->tag->selectStatic(array('params[show_image]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Liên kết ảnh</label>
							<?= $this->tag->setDefaults(array('params[link_image]'=>1));?>
							<?= $this->tag->setDefaults(array('params[link_image]'=>$params['link_image']));?>
							<?= $this->tag->selectStatic(array('params[link_image]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Hiển thị tiêu đề</label>
							<?= $this->tag->setDefaults(array('params[show_title]'=>1));?>
							<?= $this->tag->setDefaults(array('params[show_title]'=>$params['show_title']));?>
							<?= $this->tag->selectStatic(array('params[show_title]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Liên kết tiêu đề</label>
							<?= $this->tag->setDefaults(array('params[link_title]'=>1));?>
							<?= $this->tag->setDefaults(array('params[link_title]'=>$params['link_title']));?>
							<?= $this->tag->selectStatic(array('params[link_title]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Số ký tự tiêu đề</label>
							<?= $this->tag->setDefaults(array('params[number_title]'=>0));?>
							<?= $this->tag->setDefaults(array('params[number_title]'=>$params['number_title']));?>
							<?= $this->tag->textField(array('params[number_title]', 'class'=>'txt_long'));?>
						</div>
						<div class="row hor half">
							<label>Hiển thị tóm tắt</label>
							<?= $this->tag->setDefaults(array('params[show_description]'=>0));?>
							<?= $this->tag->selectStatic(array('params[show_description]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Liên kết tóm tắt</label>
							<?= $this->tag->setDefaults(array('params[link_description]'=>0));?>
							<?= $this->tag->selectStatic(array('params[link_description]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Số ký tự tóm tắt</label>
							<?= $this->tag->setDefaults(array('params[number_description]'=>0));?>
							<?= $this->tag->setDefaults(array('params[number_description]'=>$params['number_description']));?>
							<?= $this->tag->textField(array('params[number_description]', 'class'=>'txt_long'));?>
						</div>
						<div class="row hor half">
							<label>Hiển thị ngày đăng tải</label>
							<?= $this->tag->setDefaults(array('params[show_published]'=>0));?>
							<?= $this->tag->setDefaults(array('params[show_published]'=>$params['show_published']));?>
							<?= $this->tag->selectStatic(array('params[show_published]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Hiển thị lượt xem</label>
							<?= $this->tag->setDefaults(array('params[show_hits]'=>0));?>
							<?= $this->tag->setDefaults(array('params[show_hits]'=>$params['show_hits']));?>
							<?= $this->tag->selectStatic(array('params[show_hits]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Phân trang</label>
							<?= $this->tag->setDefaults(array('params[show_paginator]'=>0));?>
							<?= $this->tag->setDefaults(array('params[show_paginator]'=>$params['show_paginator']));?>
							<?= $this->tag->selectStatic(array('params[show_paginator]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Loại phân trang</label>
							<?= $this->tag->setDefaults(array('params[style_paginator]'=>0));?>
							<?= $this->tag->setDefaults(array('params[style_paginator]'=>$params['style_paginator']));?>
							<?= $this->tag->selectStatic(array('params[style_paginator]', array('0'=>'Bình thường', '1'=>'Xem thêm'), 'class'=>'long'));?>
						</div>
					</fieldset>
				</div>
			</div>
			<footer>
				<div class="submit_link">
					<input type="submit" value="Cập nhật" class="btn">
					<?= $this->tag->linkTo(array("admin/menu-item/show/{$menu_item->menu_id}", 'Trở lại', 'class'=>'btn'));?>
				</div>
			</footer>
		</form>
	</div>