	<?php $this->flashSession->output() ?>
	<div class="module width_full">
		<?= $this->tag->form("{$uri}editelement/{$element->id}"); ?>
			<div class="module_header">
				<h3 class="table_title"><?= $title_action; ?></h3>
			</div>
			
			<div class="module_content">
				<ul class="tab-row">
					<li>Thông tin chính</li>
					<li>Cấu hình</li>
				</ul>
				<div class="tab-group">
					<fieldset class="tab-content main">
						<div class="row hor">
							<label>Chức năng</label>
							<?= $this->tag->setDefaults(array('type'=>$element->type));?>
							<?= $this->tag->textField(array('type', 'readonly'=>true, 'class'=>'txt_long'));?>
						</div>
						<div class="row hor">
							<label>Tiêu đề</label>
							<?= $this->tag->setDefaults(array('name'=>$element->name));?>
							<?= $this->tag->textField(array('name', $element->name, 'class'=>'txt_long'));?>
						</div>
						<div class="row hor">
							<label>Hiển thị tiêu đề</label>
							<?= $this->tag->setDefaults(array('showtitle'=>$element->showtitle));?>
							<?= $this->tag->selectStatic(array('showtitle', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor">
							<label>Kích hoạt</label>
							<?= $this->tag->setDefaults(array('status'=>$element->status));?>
							<?= $this->tag->selectStatic(array('status', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor">
							<label>Vị trí</label>
							<?= $this->tag->setDefaults(array('posi'=>$element->posi));?>
							<?= $this->tag->textField(array('posi', 'class'=>'txt_long'));?>
						</div>
						<div class="row hor">
							<label>Thứ tự</label>
							<?= $this->tag->setDefaults(array('position'=>$element->position));?>
							<?= $this->tag->textField(array('position', 'class'=>'txt_long'));?>
						</div>
						<div class="row hor half">
							<label>Hình ảnh</label>
							<?= $this->tag->setDefaults(array('image'=>$element->image));?>
							<?= $this->tag->textField(array('image', 'class'=>'button'));?>
							<span class="input-group-btn">
		                    	<button type="button" class="btn btn-default fileBrowse" data-target="image"><i class="fa fa-folder-open"></i> Browse</button>
		                    </span>
						</div>
					</fieldset>

					<fieldset class="tab-content config">
						<div class="row hor half">
							<label>Loại hiển thị</label>
							<?php $options = array(0=>'Tin mới nhất', 1=>'Tin nổi bật', 2=>'Tin xem nhiều');?>
							<?= $this->tag->setDefaults(array('params[type]'=>$params['type']));?>
							<?= $this->tag->selectStatic(array('params[type]', $options, 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Dạng hiển thị</label>
							<?php $options = array(0=>'Cố định', 1=>'Slide Nivo', 2=>'CarouFredSel');?>
							<?= $this->tag->setDefaults(array('params[show_with]'=>$params['show_with']));?>
							<?= $this->tag->selectStatic(array('params[show_with]', $options, 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Hiển thị theo</label>
							<?php $options = array(0=>'Danh sách bài viết', 1=>'Chọn bài viết', 2=>'Kênh thông tin - bài viết');?>
							<?= $this->tag->setDefaults(array('params[show]'=>$params['show']));?>
							<?= $this->tag->selectStatic(array('params[show]', $options, 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>CarouFredSel</label>
							<?php $options = array(0=>'Cơ bản', 1=>'Thanh thời gian', 2=>'Nút trước sau', 3=>'Tất cả');?>
							<?= $this->tag->setDefaults(array('params[caroufredsel]'=>$params['caroufredsel']));?>
							<?= $this->tag->selectStatic(array('params[caroufredsel]', $options, 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Kênh thông tin</label>
							<?php $temp = explode(',', $params['category']);?>
							<?php $this->tag->setDefaults(array('params[category][]'=>$temp));?>
							<?= $this->tag->selectStatic(array('params[category][]', $category, 'size'=>9, 'multiple'=>true, 'class'=>'medium listbox'));?>
						</div>
						<div class="row hor half">
							<label>Mã bài viết</label>
							<?= $this->tag->setDefaults(array('params[itemid]'=>$params['itemid']));?>
							<?= $this->tag->textField(array('params[itemid]', 'class'=>'txt_long'));?>
						</div>
						<div class="row hor half">
							<label>Số phần tử</label>
							<?= $this->tag->setDefaults(array('params[items]'=>$params['items']));?>
							<?= $this->tag->textField(array('params[items]', 'class'=>'txt_long'));?>
						</div>
						<div class="row hor half">
							<label>Hiển thị ảnh</label>
							<?= $this->tag->setDefaults(array('params[show_image]'=>1));?>
							<?= $this->tag->setDefaults(array('params[show_image]'=>$params['show_image']));?>
							<?= $this->tag->selectStatic(array('params[show_image]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Liên kết ảnh</label>
							<?= $this->tag->setDefaults(array('params[link_image]'=>1));?>
							<?= $this->tag->setDefaults(array('params[link_image]'=>$params['link_image']));?>
							<?= $this->tag->selectStatic(array('params[link_image]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Hiển thị tiêu đề</label>
							<?= $this->tag->setDefaults(array('params[show_title]'=>1));?>
							<?= $this->tag->setDefaults(array('params[show_title]'=>$params['show_title']));?>
							<?= $this->tag->selectStatic(array('params[show_title]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Liên kết tiêu đề</label>
							<?= $this->tag->setDefaults(array('params[link_title]'=>1));?>
							<?= $this->tag->setDefaults(array('params[link_title]'=>$params['link_title']));?>
							<?= $this->tag->selectStatic(array('params[link_title]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Số ký tự tiêu đề</label>
							<?= $this->tag->setDefaults(array('params[number_title]'=>0));?>
							<?= $this->tag->setDefaults(array('params[number_title]'=>$params['number_title']));?>
							<?= $this->tag->textField(array('params[number_title]', 'class'=>'txt_long'));?>
						</div>
						<div class="row hor half">
							<label>Hiển thị tóm tắt</label>
							<?= $this->tag->setDefaults(array('params[show_description]'=>0));?>
							<?= $this->tag->selectStatic(array('params[show_description]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Liên kết tóm tắt</label>
							<?= $this->tag->setDefaults(array('params[link_description]'=>0));?>
							<?= $this->tag->selectStatic(array('params[link_description]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Số ký tự tóm tắt</label>
							<?= $this->tag->setDefaults(array('params[number_description]'=>0));?>
							<?= $this->tag->setDefaults(array('params[number_description]'=>$params['number_description']));?>
							<?= $this->tag->textField(array('params[number_description]', 'class'=>'txt_long'));?>
						</div>
						<div class="row hor half">
							<label>Hiển thị ngày đăng tải</label>
							<?= $this->tag->setDefaults(array('params[show_published]'=>0));?>
							<?= $this->tag->setDefaults(array('params[show_published]'=>$params['show_published']));?>
							<?= $this->tag->selectStatic(array('params[show_published]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
						<div class="row hor half">
							<label>Hiển thị lượt xem</label>
							<?= $this->tag->setDefaults(array('params[show_hits]'=>0));?>
							<?= $this->tag->setDefaults(array('params[show_hits]'=>$params['show_hits']));?>
							<?= $this->tag->selectStatic(array('params[show_hits]', array('0'=>'Không', '1'=>'Có'), 'class'=>'long'));?>
						</div>
					</fieldset>
				</div>
			</div>
			<footer>
				<div class="submit_link">
					<input type="submit" value="Cập nhật" class="btn">
					<?= $this->tag->linkTo(array("{$uri}index", 'Trở lại', 'class'=>'btn'));?>
				</div>
			</footer>
		</form>
	</div>